name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: ""
        type: ""
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      languages: |-
        - go: ./go-sdk/
        - python: ./python-sdk/
        - typescript: ./ts-sdk/
        - java: ./java-sdk/
      mode: pr
      openapi_doc_location: https://raw.githubusercontent.com/forem/forem/db821a806f1f150b69a219a1bf551b73113a9ee7/swagger/v1/api_v1.json
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
